name: Tests and Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker compose build

      - name: Start Database and Wait
        run: |
          docker compose up -d db
          docker compose exec -T db sh -c 'until pg_isready -h localhost -p 5432; do echo "Waiting for postgres..."; sleep 2; done'

      - name: Run tests with coverage
        run: |
          docker compose run -T --rm web pytest --cov=sql --cov-report=term-missing > coverage_report.txt
          echo "### 📊 Отчет по покрытию тестами" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat coverage_report.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Check coverage threshold
        run: |
          docker compose run -T --rm web pytest --cov=sql --cov-fail-under=80

      - name: Cleanup
        if: always()
        run: docker compose down
        
